spring.application.name=online-tiffin-service

# spring.profiles.active=local

#DB configuration
spring.datasource.url= jdbc:mysql://${JDBC_HOST}:${JDBC_PORT}/${JDBC_DB}?ssl-mode=REQUIRED
spring.datasource.username= ${JDBC_USERNAME}
spring.datasource.password= ${JDBC_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.initialization-fail-timeout=5000

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

#Sending Email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

#Cloudinary configurations
config.cloudinary.cloud.name=${CLOUDINARY_NAME}
config.cloudinary.cloud.key= ${CLOUDINARY_KEY}
config.cloudinary.cloud.secret=${CLOUDINARY_SECRET}


spring.main.lazy-initialization=true
# minimum number of idle (unused) connections HikariCP tries to keep ready.
spring.datasource.hikari.minimum-idle=2

locationiq.accesstoken = ${LOCATIONIQ_ACCESS_TOKEN}